# File: .stylua.toml

# Set the number of spaces to use for indentation.
# The default is 2, this changes it to 4.
indent_width = 2

# Explicitly set the indentation type to Spaces (this is the default).
indent_type = "Spaces"


# --- Optional but Recommended Settings ---

# You can also set other common options here.
# For example, the maximum line length before wrapping.
# column_width = 120

# How to handle quotes for strings.
# quote_style = "Auto" # "Auto", "Single", "Double"
